### ISSUE TITLE
crtl -d does a  SEGV

### ISSUE THREAD

**Issue by znichola** [sophiakoulen/minishell#38]
```bash
minishell$ ^DAddressSanitizer:DEADLYSIGNAL
=================================================================
==24065==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010429c473 bp 0x7ffeeb974570 sp 0x7ffeeb9744c0 T0)
==24065==The signal is caused by a READ memory access.
==24065==Hint: address points to the zero page.
    #0 0x10429c473 in lexer tokenizer.c:83
    #1 0x10429c229 in construct_tok_list tokenizer.c:110
    #2 0x104291446 in interactive_shell main.c:66
    #3 0x10429127b in main main.c:33
    #4 0x7fff6cf91cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

==24065==Register values:
rax = 0x0000000000000000  rbx = 0x00007ffeeb9745c0  rcx = 0x0000000000000000  rdx = 0x0000100000000000  
rdi = 0x00007ffeeb974500  rsi = 0x0000100000000000  rbp = 0x00007ffeeb974570  rsp = 0x00007ffeeb9744c0  
 r8 = 0x0000000000000000   r9 = 0x0000000105153780  r10 = 0x0000000000000000  r11 = 0x0000000000000246  
r12 = 0x0000000000000000  r13 = 0x0000000000000000  r14 = 0x0000000000000000  r15 = 0x0000000000000000  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV tokenizer.c:83 in lexer
==24065==ABORTING
[1]    24065 abort      ./minishell
```

**Comment by znichola** [comment]
was fixed at some point, good job team.
