### ISSUE TITLE
SEGV on here doc for simple command

### ISSUE THREAD

**Issue by znichola** [sophiakoulen/minishell#48]
```bash
minishell$ echo <<end
> AddressSanitizer:DEADLYSIGNAL
=================================================================
==90668==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000100c5f7cb bp 0x7ffeeefa4360 sp 0x7ffeeefa4360 T0)
==90668==The signal is caused by a READ memory access.
==90668==Hint: address points to the zero page.
    #0 0x100c5f7cb in ft_strncmp+0x5b (minishell:x86_64+0x1000047cb)
    #1 0x100c67fe1 in is_delim heredoc.c:83
    #2 0x100c67e93 in do_single_heredoc heredoc.c:63
    #3 0x100c67d4f in do_all_heredocs heredoc.c:37
    #4 0x100c6b64f in simple_command simple_cmd.c:31
    #5 0x100c6b296 in exec_pipeline exec_pipeline.c:29
    #6 0x100c5fbba in interactive_shell main.c:78
    #7 0x100c5f8eb in main main.c:33
    #8 0x7fff6cf91cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

==90668==Register values:
rax = 0x0000000000000000  rbx = 0x00007ffeeefa43e0  rcx = 0x0000000000000000  rdx = 0x0000000000000000  
rdi = 0x0000000000000000  rsi = 0x00006020000009b0  rbp = 0x00007ffeeefa4360  rsp = 0x00007ffeeefa4360  
 r8 = 0x0000000101b237a0   r9 = 0x0000000101b23780  r10 = 0x0000000000000000  r11 = 0x0000000000000246  
r12 = 0x0000000000000000  r13 = 0x0000000000000000  r14 = 0x0000000000000000  r15 = 0x0000000000000000  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (minishell:x86_64+0x1000047cb) in ft_strncmp+0x5b
==90668==ABORTING
[1]    90668 abort      ./minishell
```

**Comment by sophiakoulen** [comment]
Fixed with fe165a1146568f7a65d90c91423f5b599fc6850e i think.
